---
- name: playbook for installing, configuring and restarting apache2
  hosts: all
  become: yes
  tasks: 
   - name: install apache2
     apt:
      name: apache2
      state: present
      update_cache: yes
   - name: change the default content
     copy:
      content: "<h1>Hello World</h1>"
      dest: /var/www/html/index.html
   - name: restart apache2
     service:
      name: apache2
      state: restarted
