---
- name: create tomcat container on managed nodes
  hosts: all
  tasks:
   - name: start tomcat as a container
     docker_container:
      image: tomcat
      name: mytomcat
      ports: 
       - 7878:8080
   - name: stop tomcat container
     docker_container:
      name: mytomcat
      state: stopped
   - name: delete the container
     docker_container:
      name: mytomcat
      state: absent
