---
- name: This playbook contains a play that is for installing tree
  hosts: all
  tasks:
   - name: install tree package
     apt:
      name: tree
      state: present
      update_cache: yes
...
