---
- name: install tomcat on managed nodes
  hosts: 172.31.62.195
  tasks:
   - block:
     - name: install tomcat7
       apt:
        name: tomcat7
        state: present
        update_cache: yes
     rescue:
      - name: install tomcat9
        apt:
         name: tomcat9
         state: present
         update_cache: yes
     always:
      - name: install tomcat9
        apt:
         name: tomcat9
         state: present
