---
- name: playbook to create user and a file in user's workspace
  hosts: mygroup
  tasks:
   - name: create a user
     user:
      name: "{{a}}"
      password: "{{b}}"
      home: "{{c}}"
      comment: "{{d}}"
      shell: "{{e}}"
   - name: create a file in user's workspace
     file:
      name: "{{f}}"
      state: "{{g}}"
   - name: install git
     apt:
      name: "{{i}}"
      state: "{{h}}"
      update_cache: "{{j}}"
