---
- name: playbook for creating 5 nginx containers
  hosts: all
  tasks: 
   - name: start nginx containers
     docker_container:
      image: nginx
      name: "nginx_c{{item}}"
     with_sequence: count=5
